/**
 * Single source for the environment tool's wording: the tool description,
 * the one-line methodology section, and the full help text. Following the
 * progressive-disclosure doctrine, only the one-liner lives in the system
 * prompt; the model pulls HELP_TEXT on demand via action=help.
 *
 * @module @deepseek-ai/dsh-ops-tool-environment
 */

export const HELP_POINTER = 'Call environment action=help for full usage.'

export const TOOL_DESCRIPTION =
  'Read the environment inventory: which middleware runs on which registered k8s cluster, and best-effort relation edges between apps and middleware. ' +
  'Actions: overview (all clusters, compact), show (one cluster, details + edges; narrow with the optional namespace and name filters instead of paging a large output), refresh (re-scan now), help (full usage). ' +
  'Data comes from ~/.dsh-ops/environment.yaml, refreshed automatically when older than its TTL — reads are cheap, prefer overview over blind kubectl exploration.'

/** The one-line system-prompt section (registered through ops-prompts). */
export const STATIC_PROMPT = [
  '## environment — 环境清单',
  `排查环境问题前先 \`environment\` action=overview 看环境全貌（集群/中间件/关联边），不要从零 kubectl 摸索。${HELP_POINTER}`,
].join('\n')

export const HELP_TEXT = `# environment — environment inventory

The inventory maps every k8s cluster registered in ops-access: workloads,
services, middleware instances (classified by image/chart/label), and
best-effort relation edges (who connects to whom). It is regenerated by
deterministic scans — no LLM guessing — and persisted at
~/.dsh-ops/environment.yaml with a per-cluster scannedAt timestamp.

## Actions

- overview — all clusters, compact: middleware counts by type, unknown
  workload count, stale flag, scan time. Start here before any
  environment-related investigation.
- show — one cluster, full detail. Requires the cluster parameter (a
  cluster name from overview / list_access). Returns middleware instances
  (type/namespace/workload/service entries), the unknown bucket
  (unrecognized workloads, still listed), and relation edges. Optional
  filters narrow the lists: namespace (exact match) and name (substring,
  case-insensitive; ANDed together). When filtering, edges are kept only
  when their workload endpoint survives — for fronts edges (Service →
  workload) that endpoint is the "to" side.
- refresh — re-scan every registered k8s cluster now. A cluster that is
  unreachable keeps its previous section, marked stale. Read-only: the
  scan resolves the ro credential tier only.
- help — this text.

## Freshness

Sections older than the TTL (default 1h) are re-scanned automatically on
the next overview/show call — you never trigger scans explicitly except
when you know the environment just changed (then call refresh).

## Reading edges

- uses-middleware  app → middleware instance (targetType is the middleware type)
- uses-service     app → Service (an address seen in env/ConfigMap values)
- fronts           Service → workload it selects
- references-secret  app → Secret, reference NAME only — values are never read

## Unknown bucket

Workloads the classification table cannot identify are listed under
unknown with name and image — they are not errors. Site-specific
components can be taught via ~/.dsh-ops/environment-rules.yaml.

## Monitoring corroboration

When a cluster has a discoverable Prometheus service (monitoring
namespace, port 9090), entries carry monitoring: { up, down } counts
scraped from /api/v1/targets over a short-lived kubectl port-forward.
A down count means Prometheus sees the instance failing — investigate
those first. Clusters without Prometheus simply have no monitoring data.

## Anomalies

Each cluster section carries rule-detected anomalies (generic k8s
semantics only, zero LLM):

- cross-namespace-ref (info) — a workload references a Service in a
  DIFFERENT namespace. Often legitimate for shared infrastructure, but a
  prime suspect when an environment behaves like another one (e.g. a
  test environment pointing at another namespace's database).
- service-no-backend (warning) — a Service has a pod selector but its
  Endpoints have zero ready addresses: nothing answers on it.

overview lists all anomalies in one section; show annotates the involved
entries in place with [!].`
