/**
 * Inventory persistence — `~/.dsh-ops/environment.yaml`.
 *
 * The file is auto-generated (header says so), segmented per cluster, and
 * each section carries the scan timestamp. Freshness discipline lives here:
 * refreshInventory re-scans every target cluster; a cluster that fails
 * (unreachable, timeout, kubectl error) keeps its previous section with
 * `stale: true` and a sanitized `lastError` — the section never disappears
 * and the failure never aborts the other clusters.
 *
 * Security discipline: the kubeconfig path is used to run kubectl and then
 * scrubbed out of every error before it is stored; Secret values never
 * enter the pipeline (see scanner.ts). What lands in this file is safe to
 * show the model verbatim.
 *
 * @module @deepseek-ai/dsh-ops-tool-environment
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname } from 'node:path'
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml'
import { classifyWorkload, expandHome, isMiddlewareType } from './classify.js'
import { detectAnomalies } from './anomalies.js'
import { matchTargetsToWorkloads } from './prometheus.js'
import type { SpawnFn } from './prometheus.js'
import { buildRelations } from './relations.js'
import { scanCluster, scrubKubeconfigPath } from './scanner.js'
import type { ExecFn } from './scanner.js'
import type {
  ClassifiedWorkload,
  ClusterInventory,
  ClusterScan,
  MiddlewareInstance,
} from './types.js'

export const DEFAULT_INVENTORY_FILE = '~/.dsh-ops/environment.yaml'

const HEADER = [
  '# AUTO-GENERATED by @deepseek-ai/dsh-ops-tool-environment — DO NOT EDIT BY HAND.',
  '# Regenerated from live k8s scans; manual changes are overwritten on the next refresh.',
].join('\n')

/** One cluster section: the inventory plus freshness markers. */
export interface InventorySection extends ClusterInventory {
  /** Set when the last refresh failed and this section holds older data. */
  stale?: boolean
  /** Sanitized message of the last refresh failure (no credential paths). */
  lastError?: string
}

/** The whole environment.yaml document. */
export interface EnvironmentInventory {
  version: 1
  clusters: Record<string, InventorySection>
}

/** A cluster to refresh: profile id plus its resolved kubeconfig path. */
export interface RefreshTarget {
  cluster: string
  kubeconfigPath: string
}

export interface RefreshOptions {
  /** Inventory file path; defaults to ~/.dsh-ops/environment.yaml. */
  file?: string
  /** Injectable kubectl runner (tests); defaults to spawning kubectl. */
  exec?: ExecFn
  /** Injectable port-forward spawn for the Prometheus scrape (tests). */
  spawn?: SpawnFn
  /** Injectable fetch for the Prometheus scrape (tests). */
  fetchFn?: typeof fetch
  /** User classification rules file; defaults to ~/.dsh-ops/environment-rules.yaml. */
  userRulesFile?: string
  /** Timestamp source (tests). */
  now?: Date
}

const byNsName = <T extends { namespace: string, name: string }>(a: T, b: T) =>
  a.namespace.localeCompare(b.namespace) || a.name.localeCompare(b.name)

/**
 * Assemble the per-cluster inventory from a raw scan: classify every
 * workload, collect middleware instances with their Service entries, and
 * derive relation edges. Deterministic — output lists are sorted so the
 * same cluster scanned twice yields the same section.
 */
export function buildClusterInventory(
  scan: ClusterScan,
  opts: { userRulesFile?: string } = {},
): ClusterInventory {
  const classified: ClassifiedWorkload[] = scan.workloads
    .map(w => ({ ...w, type: classifyWorkload(w, { userRulesFile: opts.userRulesFile }) }))
    .sort(byNsName)

  // Prometheus corroboration: attach up/down counts per workload (best-effort;
  // absent when the cluster had no scrapable Prometheus).
  if (scan.prometheus !== undefined) {
    const statuses = matchTargetsToWorkloads(classified, scan.prometheus.targets)
    for (const w of classified) {
      const status = statuses.get(`${w.namespace}/${w.name}`)
      if (status !== undefined) w.monitoring = status
    }
  }

  const edges = buildRelations({ scan, classified })
  const services = [...scan.services].sort(byNsName)

  const middleware: MiddlewareInstance[] = []
  for (const w of classified) {
    if (!isMiddlewareType(w.type)) continue
    const serviceEntries = edges
      .filter(e => e.kind === 'fronts' && e.to.kind === w.kind && e.to.namespace === w.namespace && e.to.name === w.name)
      .map(e => e.from.name)
      .sort()
    const instance: MiddlewareInstance = {
      type: w.type,
      namespace: w.namespace,
      workload: w.name,
      workloadKind: w.kind,
      images: [...w.images].sort(),
      serviceEntries,
    }
    if (w.monitoring !== undefined) instance.monitoring = w.monitoring
    middleware.push(instance)
  }
  middleware.sort((a, b) => a.namespace.localeCompare(b.namespace) || a.workload.localeCompare(b.workload))

  edges.sort((a, b) =>
    a.kind.localeCompare(b.kind)
    || a.from.namespace.localeCompare(b.from.namespace)
    || a.from.name.localeCompare(b.from.name)
    || a.to.name.localeCompare(b.to.name)
    || a.via.localeCompare(b.via))

  const inventory: ClusterInventory = {
    scannedAt: scan.scannedAt,
    middleware,
    anomalies: detectAnomalies({ edges, services, endpoints: scan.endpoints }),
    workloads: classified,
    services,
    ingresses: [...scan.ingresses].sort(byNsName),
    edges,
  }
  if (scan.prometheus !== undefined) inventory.prometheusService = scan.prometheus.service
  return inventory
}

/** Read the inventory file. Returns null when it does not exist or is malformed. */
export async function readInventory(file: string = DEFAULT_INVENTORY_FILE): Promise<EnvironmentInventory | null> {
  let text: string
  try {
    text = await readFile(expandHome(file), 'utf8')
  } catch {
    return null
  }
  try {
    const doc = parseYaml(text) as EnvironmentInventory | null
    if (!doc || typeof doc !== 'object' || typeof doc.clusters !== 'object' || doc.clusters === null) {
      return null
    }
    return doc
  } catch {
    return null
  }
}

/** Serialize and write the inventory, prepending the do-not-edit header. */
async function writeInventory(file: string, inventory: EnvironmentInventory): Promise<void> {
  const path = expandHome(file)
  await mkdir(dirname(path), { recursive: true })
  const body = stringifyYaml(inventory)
  await writeFile(path, `${HEADER}\n${body}`, 'utf8')
}

function emptySection(scannedAt: string): InventorySection {
  return { scannedAt, middleware: [], anomalies: [], workloads: [], services: [], ingresses: [], edges: [] }
}

/**
 * Refresh the inventory for the given clusters.
 *
 * Per cluster: scan + assemble + replace the section. On failure the
 * previous section survives with `stale: true` and a sanitized lastError;
 * a cluster with no previous data gets an empty stale section so the gap
 * is visible. Sections of clusters not in `targets` are left untouched.
 * Never throws — per-cluster failures are folded into their sections.
 */
export async function refreshInventory(
  targets: RefreshTarget[],
  opts: RefreshOptions = {},
): Promise<EnvironmentInventory> {
  const file = opts.file ?? DEFAULT_INVENTORY_FILE
  const now = opts.now ?? new Date()
  const existing = await readInventory(file)
  const clusters: Record<string, InventorySection> = { ...(existing?.clusters ?? {}) }

  await Promise.all(targets.map(async (target) => {
    try {
      const scan = await scanCluster({
        cluster: target.cluster,
        kubeconfigPath: target.kubeconfigPath,
        exec: opts.exec,
        spawn: opts.spawn,
        fetchFn: opts.fetchFn,
        now,
      })
      clusters[target.cluster] = buildClusterInventory(scan, { userRulesFile: opts.userRulesFile })
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err)
      // Defense in depth: scanner errors are pre-scrubbed; scrub again here so
      // no code path can persist the real kubeconfig path.
      const lastError = scrubKubeconfigPath(raw, target.kubeconfigPath)
      const previous = clusters[target.cluster] ?? emptySection(now.toISOString())
      clusters[target.cluster] = { ...previous, stale: true, lastError }
    }
  }))

  const inventory: EnvironmentInventory = {
    version: 1,
    clusters: Object.fromEntries(Object.entries(clusters).sort(([a], [b]) => a.localeCompare(b))),
  }
  await writeInventory(file, inventory)
  return inventory
}
